add compile

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -9,6 +9,25 @@ on:
 jobs:
 
     coding-style:
+        runs-on: ubuntu-latest
+        container:
+            image: ghcr.io/epitech/coding-style-checker:latest
+        steps:
+          - name: Checkout GH repo
+            uses: actions/checkout@v4
+
+          - name: Run coding-style.sh
+            run: check.sh $(pwd) $(pwd)
+
+          - name: Report banana result
+            run: |
+              NB_ERROR=$(cat coding-style-reports.log | wc -l)
+              if [ $NB_ERROR -gt 0]; then
+                  ERROR=$(cat coding-style-reports.log)
+                  echo "::error title=$NB_ERROR errors found::$ERROR"
+                  exit 1
+              fi
+              exit 0
 
     compile:
         runs-on: ubuntu-latest
